### ISSUE TITLE
ecflow installs fine on Gaea, but cannot run ecflow_ui

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#168]
Starting up ecflow_ui fails with
```
Dom.Heinzeller@gaea12:~> ecflow_ui
ecflow_ui: EXIT on ERROR (line 1), exit status 134, starting 'cleanup'
Last 50 lines of log file:
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl.

/lustre/f2/scratch/esrl/Dom.Heinzeller/spack-stack-update-spack-v0.18/envs/jedi-all-intel-2021.3.0/install/intel/2021.3.0/ecflow-5.8.3-4vlhsd3/bin/ecflow_ui: line 406:  1663 Aborted                 (core dumped) ${ECFLOWUI_USER_START_CMD} "$exe"

Last 50 lines of user interaction log file:
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl.

/lustre/f2/scratch/esrl/Dom.Heinzeller/spack-stack-update-spack-v0.18/envs/jedi-all-intel-2021.3.0/install/intel/2021.3.0/ecflow-5.8.3-4vlhsd3/bin/ecflow_ui: line 406:  1663 Aborted                 (core dumped) ${ECFLOWUI_USER_START_CMD} "$exe"
```

After setting `export QT_DEBUG_PLUGINS=1`:
```
/lustre/f2/scratch/esrl/Dom.Heinzeller/spack-stack-update-spack-v0.18/envs/jedi-all-intel-2021.3.0/install/intel/2021.3.0/ecflow-5.8.3-4vlhsd3/bin/ecflow_ui: line 406: 48933 Aborted                 (core dumped) ${ECFLOWUI_USER_START_CMD} "$exe"

Last 50 lines of user interaction log file:
    },
    "archreq": 0,
    "className": "QWaylandXCompositeEglPlatformIntegrationPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("wayland-xcomposite-egl")
QFactoryLoader::QFactoryLoader() looking at "/lustre/f2/pdata/esrl/gsd/spack-stack/qt-5.15.3/plugins/platforms/libqwayland-xcomposite-glx.so"
Found metadata in lib /lustre/f2/pdata/esrl/gsd/spack-stack/qt-5.15.3/plugins/platforms/libqwayland-xcomposite-glx.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "wayland-xcomposite-glx"
        ]
    },
    "archreq": 0,
    "className": "QWaylandXCompositeGlxPlatformIntegrationPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("wayland-xcomposite-glx")
QFactoryLoader::QFactoryLoader() looking at "/lustre/f2/pdata/esrl/gsd/spack-stack/qt-5.15.3/plugins/platforms/libqwebgl.so"
Found metadata in lib /lustre/f2/pdata/esrl/gsd/spack-stack/qt-5.15.3/plugins/platforms/libqwebgl.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "webgl"
        ]
    },
    "archreq": 0,
    "className": "QWebGLIntegrationPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("webgl")
QFactoryLoader::QFactoryLoader() checking directory path "/lustre/f2/scratch/esrl/Dom.Heinzeller/spack-stack-update-spack-v0.18/envs/jedi-all-intel-2021.3.0/install/intel/2021.3.0/ecflow-5.8.3-4vlhsd3/bin/platforms" ...
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl.

/lustre/f2/scratch/esrl/Dom.Heinzeller/spack-stack-update-spack-v0.18/envs/jedi-all-intel-2021.3.0/install/intel/2021.3.0/ecflow-5.8.3-4vlhsd3/bin/ecflow_ui: line 406: 48933 Aborted                 (core dumped) ${ECFLOWUI_USER_START_CMD} "$exe
```

Weird that it says that there is an empty path to search for plugins, but then it finds the plugins anyway (or is it looking in the OS/default qt plugin dir instead of the external qt5?

To be investigated ...

**Comment by climbfuji** [comment]
The ecflow server also doesn't run:
```
Dom.Heinzeller@gaea12:~> ecflow_start.sh
[16:49:34 2.6.2022] Request( --ping ), Failed to connect to gaea12:21751. After 2 attempts. Is the server running ?

Thu Jun  2 16:49:34 UTC 2022

User "20251" attempting to start ecf server on "gaea12" using ECF_PORT "21751" and with:
ECF_HOME     : "/ncrc/home2/Dom.Heinzeller/ecflow_server"
ECF_LOG      : "gaea12.21751.ecf.log"
ECF_CHECK    : "gaea12.21751.check"
ECF_CHECKOLD : "gaea12.21751.check.b"
ECF_OUT      : "/dev/null"

client version is Ecflow version(5.8.3) boost(1.78.0) compiler(intel 2021) protocol(JSON cereal 1.3.0) openssl(enabled) Compiled on Jun  1 2022 18:59:54
Checking if the server is already running on gaea12 and port 21751
[16:49:36 2.6.2022] Request( --ping ), Failed to connect to gaea12:21751. After 2 attempts. Is the server running ?


Backing up check point and log files

OK starting ecFlow server...

Placing server into RESTART mode...
Connection::async_write, exception Trying to save an unregistered polymorphic type (CtsCmd).
Make sure your type is registered with CEREAL_REGISTER_TYPE and that the archive you are using was included (and registered with CEREAL_REGISTER_ARCHIVE) prior to calling CEREAL_REGISTER_TYPE.
If your type is already registered and you still see this error, you may need to use CEREAL_REGISTER_DYNAMIC_INIT., in client data:

[16:49:41 2.6.2022] ClientInvoker: Connection error: (Client::handle_write: error (Invalid argument ) for request( --restart ) on gaea12:21751)
```
I have seen (and fixed) this error befor, probably even on gaea, just need to remember what I did.

**Comment by Uawkm** [comment]
Excuse me. Do you solve the prblem about ecflow_ui now? I have the same peoblem like you on the linux system.
Regards！

**Comment by climbfuji** [comment]
> Excuse me. Do you solve the prblem about ecflow_ui now? I have the same peoblem like you on the linux system.
> Regards！

I fixed that on other systems so far by installing qt using the qt online installer (see here: https://wiki.qt.io/Online_Installer_Help). Also, the latest documentation for spack-stack has instructions in the maintainer section, look for the NASA discover machine. Start from the maintainer section, it then works backwards to the prerequisites section. Should be all in there.

If you don't care about using spack and just want a version, you can also try ecflow that comes with the anaconda/miniconda distributions?

**Comment by climbfuji** [comment]
> The ecflow server also doesn't run:
> 
> ```
> Dom.Heinzeller@gaea12:~> ecflow_start.sh
> [16:49:34 2.6.2022] Request( --ping ), Failed to connect to gaea12:21751. After 2 attempts. Is the server running ?
> 
> Thu Jun  2 16:49:34 UTC 2022
> 
> User "20251" attempting to start ecf server on "gaea12" using ECF_PORT "21751" and with:
> ECF_HOME     : "/ncrc/home2/Dom.Heinzeller/ecflow_server"
> ECF_LOG      : "gaea12.21751.ecf.log"
> ECF_CHECK    : "gaea12.21751.check"
> ECF_CHECKOLD : "gaea12.21751.check.b"
> ECF_OUT      : "/dev/null"
> 
> client version is Ecflow version(5.8.3) boost(1.78.0) compiler(intel 2021) protocol(JSON cereal 1.3.0) openssl(enabled) Compiled on Jun  1 2022 18:59:54
> Checking if the server is already running on gaea12 and port 21751
> [16:49:36 2.6.2022] Request( --ping ), Failed to connect to gaea12:21751. After 2 attempts. Is the server running ?
> 
> 
> Backing up check point and log files
> 
> OK starting ecFlow server...
> 
> Placing server into RESTART mode...
> Connection::async_write, exception Trying to save an unregistered polymorphic type (CtsCmd).
> Make sure your type is registered with CEREAL_REGISTER_TYPE and that the archive you are using was included (and registered with CEREAL_REGISTER_ARCHIVE) prior to calling CEREAL_REGISTER_TYPE.
> If your type is already registered and you still see this error, you may need to use CEREAL_REGISTER_DYNAMIC_INIT., in client data:
> 
> [16:49:41 2.6.2022] ClientInvoker: Connection error: (Client::handle_write: error (Invalid argument ) for request( --restart ) on gaea12:21751)
> ```
> 
> I have seen (and fixed) this error befor, probably even on gaea, just need to remember what I did.

This one is solved - need to build ecflow with GNU, all Intel compilers except the new oneapi (icx, ifx, ...) compilers are having a known bug that leads to this error.

**Comment by Uawkm** [comment]
Sorgy. I can't understand the screenshot. When I use the command of ecflow_start.sh, I have the same command response. But ecflow_ui still doesn't work.



---Original---
From: "Dom ***@***.***&gt;
Date: Thu, Jul 7, 2022 10:47 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [NOAA-EMC/spack-stack] ecflow installs fine on Gaea, but cannot run ecflow_ui (Issue #168)




  
The ecflow server also doesn't run:
 ***@***.***:~&gt; ecflow_start.sh [16:49:34 2.6.2022] Request( --ping ), Failed to connect to gaea12:21751. After 2 attempts. Is the server running ? Thu Jun  2 16:49:34 UTC 2022 User "20251" attempting to start ecf server on "gaea12" using ECF_PORT "21751" and with: ECF_HOME     : "/ncrc/home2/Dom.Heinzeller/ecflow_server" ECF_LOG      : "gaea12.21751.ecf.log" ECF_CHECK    : "gaea12.21751.check" ECF_CHECKOLD : "gaea12.21751.check.b" ECF_OUT      : "/dev/null" client version is Ecflow version(5.8.3) boost(1.78.0) compiler(intel 2021) protocol(JSON cereal 1.3.0) openssl(enabled) Compiled on Jun  1 2022 18:59:54 Checking if the server is already running on gaea12 and port 21751 [16:49:36 2.6.2022] Request( --ping ), Failed to connect to gaea12:21751. After 2 attempts. Is the server running ? Backing up check point and log files OK starting ecFlow server... Placing server into RESTART mode... Connection::async_write, exception Trying to save an unregistered polymorphic type (CtsCmd). Make sure your type is registered with CEREAL_REGISTER_TYPE and that the archive you are using was included (and registered with CEREAL_REGISTER_ARCHIVE) prior to calling CEREAL_REGISTER_TYPE. If your type is already registered and you still see this error, you may need to use CEREAL_REGISTER_DYNAMIC_INIT., in client data: [16:49:41 2.6.2022] ClientInvoker: Connection error: (Client::handle_write: error (Invalid argument ) for request( --restart ) on gaea12:21751)  
I have seen (and fixed) this error befor, probably even on gaea, just need to remember what I did.
  
This one is solved - need to build ecflow with GNU, all Intel compilers except the new oneapi (icx, ifx, ...) compilers are having a known bug that leads to this error.

**Comment by Uawkm** [comment]
---Original---
From: "Dom ***@***.***&gt;
Date: Thu, Jul 7, 2022 10:47 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [NOAA-EMC/spack-stack] ecflow installs fine on Gaea, but cannot run ecflow_ui (Issue #168)




  
The ecflow server also doesn't run:
 ***@***.***:~&gt; ecflow_start.sh [16:49:34 2.6.2022] Request( --ping ), Failed to connect to gaea12:21751. After 2 attempts. Is the server running ? Thu Jun  2 16:49:34 UTC 2022 User "20251" attempting to start ecf server on "gaea12" using ECF_PORT "21751" and with: ECF_HOME     : "/ncrc/home2/Dom.Heinzeller/ecflow_server" ECF_LOG      : "gaea12.21751.ecf.log" ECF_CHECK    : "gaea12.21751.check" ECF_CHECKOLD : "gaea12.21751.check.b" ECF_OUT      : "/dev/null" client version is Ecflow version(5.8.3) boost(1.78.0) compiler(intel 2021) protocol(JSON cereal 1.3.0) openssl(enabled) Compiled on Jun  1 2022 18:59:54 Checking if the server is already running on gaea12 and port 21751 [16:49:36 2.6.2022] Request( --ping ), Failed to connect to gaea12:21751. After 2 attempts. Is the server running ? Backing up check point and log files OK starting ecFlow server... Placing server into RESTART mode... Connection::async_write, exception Trying to save an unregistered polymorphic type (CtsCmd). Make sure your type is registered with CEREAL_REGISTER_TYPE and that the archive you are using was included (and registered with CEREAL_REGISTER_ARCHIVE) prior to calling CEREAL_REGISTER_TYPE. If your type is already registered and you still see this error, you may need to use CEREAL_REGISTER_DYNAMIC_INIT., in client data: [16:49:41 2.6.2022] ClientInvoker: Connection error: (Client::handle_write: error (Invalid argument ) for request( --restart ) on gaea12:21751)  
I have seen (and fixed) this error befor, probably even on gaea, just need to remember what I did.
  
This one is solved - need to build ecflow with GNU, all Intel compilers except the new oneapi (icx, ifx, ...) compilers are having a known bug that leads to this error.

**Comment by Uawkm** [comment]
Sorry. I forget to say my compiler is GNU/LINUX



---Original---
From: "Dom ***@***.***&gt;
Date: Thu, Jul 7, 2022 10:47 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [NOAA-EMC/spack-stack] ecflow installs fine on Gaea, but cannot run ecflow_ui (Issue #168)




  
The ecflow server also doesn't run:
 ***@***.***:~&gt; ecflow_start.sh [16:49:34 2.6.2022] Request( --ping ), Failed to connect to gaea12:21751. After 2 attempts. Is the server running ? Thu Jun  2 16:49:34 UTC 2022 User "20251" attempting to start ecf server on "gaea12" using ECF_PORT "21751" and with: ECF_HOME     : "/ncrc/home2/Dom.Heinzeller/ecflow_server" ECF_LOG      : "gaea12.21751.ecf.log" ECF_CHECK    : "gaea12.21751.check" ECF_CHECKOLD : "gaea12.21751.check.b" ECF_OUT      : "/dev/null" client version is Ecflow version(5.8.3) boost(1.78.0) compiler(intel 2021) protocol(JSON cereal 1.3.0) openssl(enabled) Compiled on Jun  1 2022 18:59:54 Checking if the server is already running on gaea12 and port 21751 [16:49:36 2.6.2022] Request( --ping ), Failed to connect to gaea12:21751. After 2 attempts. Is the server running ? Backing up check point and log files OK starting ecFlow server... Placing server into RESTART mode... Connection::async_write, exception Trying to save an unregistered polymorphic type (CtsCmd). Make sure your type is registered with CEREAL_REGISTER_TYPE and that the archive you are using was included (and registered with CEREAL_REGISTER_ARCHIVE) prior to calling CEREAL_REGISTER_TYPE. If your type is already registered and you still see this error, you may need to use CEREAL_REGISTER_DYNAMIC_INIT., in client data: [16:49:41 2.6.2022] ClientInvoker: Connection error: (Client::handle_write: error (Invalid argument ) for request( --restart ) on gaea12:21751)  
I have seen (and fixed) this error befor, probably even on gaea, just need to remember what I did.
  
This one is solved - need to build ecflow with GNU, all Intel compilers except the new oneapi (icx, ifx, ...) compilers are having a known bug that leads to this error.
